# Generated by Django 6.0.1 on 2026-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(default='General', max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('total_score', models.FloatField(default=0, help_text='Total exam score')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('test', 'Test'), ('descriptive', 'Descriptive')], max_length=20)),
                ('score', models.FloatField(default=1, help_text='Score for this question')),
            ],
        ),
    ]
