# Generated by Django 6.0.1 on 2026-02-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
