# Generated by Django 6.0.1 on 2026-02-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_exam_subject_exam_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
