# Generated by Django 6.0.1 on 2026-02-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(default=1, help_text='Score for this question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_score',
            field=models.FloatField(default=0, help_text='Total exam score'),
        ),
    ]
