# Generated by Django 6.0.1 on 2026-02-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.examattempt'),
        ),
    ]
